name: Release

on: { push: { tags: ["v*"] } }

jobs:
    Generate-Docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: mattnotmitt/doxygen-action@v1
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./html
