name: Release

on: { push: { tags: ["v*"] } }

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: mattnotmitt/doxygen-action@v1

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./html

            - id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./html
                  destination_dir: ${{ steps.get_version.outputs.VERSION }}

            - uses: softprops/action-gh-release@v1
              with:
                  files: |
                      HD44780.h
                      HD44780.c
